### PR TITLE
Update build.gradle files

### PR DESCRIPTION
**Pull request by BullDog481**
Update build.gradle files so the project builds in Android Studio 4.0

### CODE REVIEW

**Comment by BullDog481** [comment]
@googlebot I signed it!

**Comment by BullDog481** [comment]
@googlebot I signed it!

**Comment by BullDog481** [comment]
Updated build.gradle to minSdkVersion 23 to fix error in KeyFileSigner.java, changed KeyFileSigner INSTANCE variable to a non-static variable and KeyFileSigner get() method to fix a memory leak error in KeyFileSigner.java.

**Comment by nic0lette** [comment]
Thanks for the PR!

> Updated build.gradle to minSdkVersion 23 to fix error in KeyFileSigner.java, changed KeyFileSigner INSTANCE variable to a non-static variable and KeyFileSigner get() method to fix a memory leak error in KeyFileSigner.java.

This also changes it so that `KeyFileSigner` isn't a singleton, and I'm not sure that doesn't have any further implications.

**Pull request closed without merging**
